services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/weatherhistory
      DB_USER: weatherhistory_user
      DB_PASSWORD: weatherhistory_pass
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: weatherhistory
      POSTGRES_USER: weatherhistory_user
      POSTGRES_PASSWORD: weatherhistory_pass
    ports:
      - 5432:5432